services:
  client:
    image: client:latest
    ports:
      - '3000:80'
    build:
      context: ./client
      dockerfile: docker/Dockerfile

  krapi:
    image: krapi:latest
    ports:
      - '8080:8080'
    build:
      context: ./krapi
      dockerfile: docker/Dockerfile

  vehicle-positions:
    image: vehicle-positions:latest
    ports:
      - '8081:8080'
    build:
      context: ./vehicle-positions
      dockerfile: docker/Dockerfile

  timetables:
    image: timetables:latest
    ports:
      - '8082:8080'
    build:
      context: ./timetables
      dockerfile: docker/Dockerfile
