services:
  client:
    image: client:latest
    ports:
      - '3000:80'
    build:
      context: ./client
      dockerfile: docker/Dockerfile

  krapi:
    image: krapi:latest
    ports:
      - '8080:8080'
    build:
      context: ./krapi/docker
      dockerfile: Dockerfile.fast
      args:
        - build_file=build.zip

  vehicle-positions:
    image: vehicle-positions:latest
    ports:
      - '8081:8080'
    build:
      context: ./vehicle-positions/docker
      dockerfile: Dockerfile.fast
      args:
        - build_file=build.zip

  timetables:
    image: timetables:latest
    ports:
      - '8082:8080'
    build:
      context: ./timetables/docker
      dockerfile: Dockerfile.fast
      args:
        - build_file=build.zip
