spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
