name: Timetables CI

on:
  push:
    branches:
      - master
    paths:
      - 'timetables/**'

  pull_request:
    branches:
      - master
      - 'features/*'
      - 'bugs/*'
    paths:
      - 'timetables/**'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./timetables

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build